name: 'build-test'
# on:
#   workflow_dispatch:

on: # rebuild any PRs and main branch changes
  push:
    branches:
      - 'releases/*'
      - 'main'
      - 'develop'
env:
  SECRET_W: ${{ secrets.SECRET_W }}
jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    container: node:10.16-jessie
    env:
      SECRET_V: ${{ secrets.SECRET_V }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
          npm run build
          env
      - run: echo $SECRET_W
