name: Git Tag
on: # rebuild any PRs and main branch changes
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: tagname=`date '+%Y/%m/%d'`
      - run: git tag ${tagname}
      - run: git push origin {tagname}
